### ISSUE TITLE
JSON support: doesn't hide non-semantic changes

### ISSUE THREAD

**Issue by cunneen** [Sysmagine/SemanticDiff#10]
**Describe the Bug**

When JSON files have the sequence of their properties changed without any semantic changes, semanticdiff is highlighting them as changes. The JSON standard specifies that object properties are unordered; some of the tools we use 

**To Reproduce**
Open the diff for JSON file with only the property order changed.

**Expected Behavior**
non-semantic changes are not highlighted

**Actual Behavior**
See screenshot

**Screenshots**
<img width="2672" alt="Screenshot 2023-03-22 at 6 15 03 pm" src="https://user-images.githubusercontent.com/1751645/226873357-f0c81a3c-be35-4d8b-b058-277a57c4ae50.png">

**Source Code**
n/a

**SemanticDiff Version**
v0.8.2

**VS Code Information**
Simply click `Help -> About -> Copy` in VS Code and paste the information:

```

Version: 1.76.2
Commit: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
Date: 2023-03-14T17:53:46.528Z (1 wk ago)
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 22.2.0
Sandboxed: No
```

**Additional Context**
n/a

**Comment by slackner** [comment]
Thanks for the report! 

Looks like the re-ordering changes are considered "too significant" to match corresponding key/value pairs correctly.

I'll try to reproduce this with a smaller example and get back to with more detail soon.

**Comment by cunneen** [comment]
Thanks! For the record, we often need to compare json files that have been parsed by a tool and later reserialised, and it would be super useful if we were able to do a semantic comparison within vscode with such property reordering not highlighted at all. Currently we are copying and pasting into jsondiff.com to achieve this.
