### ISSUE TITLE
Repos containing a `.` do not work

### ISSUE THREAD

**Issue by styfle** [Sysmagine/SemanticDiff#19]
**Describe the Bug**
Repos containing a dot (`.`) do not work.

**To Reproduce**
1. Visit https://app.semanticdiff.com
2. Enter `https://github.com/vercel/next.js/pull/51733`
3. Click "Go" button

**Expected Behavior**
Show diff

**Actual Behavior**
Error message "This URL does not belong to a GitHub PR or commit"

**Link**
You can also see a more detail error at https://app.semanticdiff.com/vercel/next.js/pull/51733/files

```
{"detail":[{"loc":["path","repo"],"msg":"string does not match regex \"^[a-zA-Z0-9_-]+$\"","type":"value_error.str.regex","ctx":{"pattern":"^[a-zA-Z0-9_-]+$"}}]}
```

**Additional Context**
Next.js is one of the most starred github repos.

There are several repos in the [top 100](https://github.com/EvanLi/Github-Ranking/blob/master/Top100/Top-100-stars.md) that contain a dot.

**Comment by mmueller2012** [comment]
Thanks for reporting the bug. As you probably already noticed, the validation regex was missing a dot. I added it and deployed a new version. It should work now.

By the way, you won't have much luck with this particular PR because SemanticDiff doesn't support `.mdx` files yet.

**Comment by styfle** [comment]
Thanks! I'll close this one and create a new issue for mdx support.

- #20
