### ISSUE TITLE
Support for the JSON file format

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [Sysmagine/SemanticDiff#2]
Support for simple formats like json, graphql, yml ...

**Comment by slackner** [comment]
Thanks a lot for your feature request, support for the JSON format would be very useful indeed! :+1: 

What kind of GraphQL files are we talking about in your case? If you are referring to GraphQL JSON files, it will probably automatically be covered by the JSON parser once it becomes available.

Regarding YAML files, I'm afraid they probably need their own separate parser. To keep the bug reports as manageable as possible, I would suggest to handle only one file format per bug report. Let's make this one about the JSON format (including various applications). I've opened a separate [bug report to handle support for the YAML format](https://github.com/Sysmagine/SemanticDiff/issues/5). Feel free to add more details about your specific YAML use case there. Thanks!

**Comment by mmueller2012** [comment]
Small update: We are currently working on JSON support. It will probably be included in the next update.

**Comment by mmueller2012** [comment]
We just released SemanticDiff 0.8.2 which has initial support for diffing JSON files. Since we are still working on optimizing SemanticDiff, the performance might not be optimal for huge files yet.

I will close this bug report, but please let us know if it works for you.
