### ISSUE TITLE
Improvements to collapsed unchanged regions

### ISSUE THREAD

**Issue by gustavoferrara** [Sysmagine/SemanticDiff#38]
Oftentimes i need to check all unchanged regions of my code and it becomes annoying having to click `Show more` 20 lines at a time.
Having a solution similar to Vscode's new diff editor would be great, essentially having a little icon which lets you expand the whole region (and be able to collapse it altogether if it's been expanded as well).
![showall](https://github.com/Sysmagine/SemanticDiff/assets/73325370/093cefbe-9681-4673-80d6-9aead39c171c)

It would be even better if somewhere along the top diff menu an option was added to outright toggle all unchanged regions
![topmenu](https://github.com/Sysmagine/SemanticDiff/assets/73325370/7a12312e-45d8-4103-9c55-17c6132aa26e)

**Comment by mmueller2012** [comment]
Thanks for the suggestion. I will look into it.

As a tip for the meantime: You can also expand by clicking on the scopes:

![image](https://github.com/Sysmagine/SemanticDiff/assets/3102472/37271620-f845-4c96-bf7f-de1a395456fe)

Depending on the structure of the file, this allows you to expand much larger regions than just 20 lines.

**Comment by mmueller2012** [comment]
We just released SemanticDiff 0.8.6 which includes both of your suggestions.

You can expand all changes between two hunks by clicking this button:

![image](https://github.com/Sysmagine/SemanticDiff/assets/3102472/1c3c5594-84d2-4ff1-8df2-16dc9da4d1ff)

And there is now a menu item to expand all hunks:

![image](https://github.com/Sysmagine/SemanticDiff/assets/3102472/d1b05232-8119-4ed4-93e2-56f9b18ebf3d)

There is currently no way to collapse individual hunks again, but you can collapse all hunks using the "Collapse Context Lines" option from the menu.

**Comment by gustavoferrara** [comment]
That's great, thanks a lot!
