### ISSUE TITLE
Add support for the Vue Single-File Component format

### ISSUE THREAD

**Issue by mmueller2012** [Sysmagine/SemanticDiff#52]
As the title implies, this issue is about adding support for the Vue SFC format in SemanticDiff.

**Comment by jccr** [comment]
I too wish this could have `.vue` file support.

It's my biggest blocker preventing me from trying it out day-to-day.

**Comment by mmueller2012** [comment]
@jccr We have just released SemanticDiff 0.9.0 with support for the Vue SFC format. See the the release [announcement](https://semanticdiff.com/blog/semanticdiff-0.9.0/) for more information.

I will close this issue, but feel free to open new issues if you encounter any Vue specific problems.

**Comment by jccr** [comment]
> @jccr We have just released SemanticDiff 0.9.0 with support for the Vue SFC format. See the the release [announcement](https://semanticdiff.com/blog/semanticdiff-0.9.0/) for more information.
> 
> I will close this issue, but feel free to open new issues if you encounter any Vue specific problems.

Thanks for this! I will give it a try
