### ISSUE TITLE
SemanticDiff fails to generate colors for certain themes and therefore doesn't load

### ISSUE THREAD

**Issue by mmueller2012** [Sysmagine/SemanticDiff#58]
SemanticDiff fails to generate a color palette for certain themes. This leads to an exception during the initialization of the webview and renders SemanticDiff unusable. The problem can be identified by the following exception in the developer console:

```
Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at a2 (script.js:16:94457)
    at Tu.updateColorTheme (script.js:16:98744)
    at new Tu (script.js:16:96840)
    at script.js:16:118631
    at script.js:16:119322
```

One theme known to trigger this problem is [Cobalt Next](https://marketplace.visualstudio.com/items?itemName=dline.CobaltNext).

**Comment by slackner** [comment]
This issue has been fixed in SemanticDiff 0.8.10. If you still encounter any issues similar to the one described above, please comment or open a new bug report.
