### ISSUE TITLE
File path is clobbered with git hash

### ISSUE THREAD

**Issue by worksofliam** [Sysmagine/SemanticDiff#7]
When looking at diffs via the GitLens Commits view, the path to the file is messed up at the top of the diff. You can see in this image that there is a long string followed by the path to the file on the right.

<img width="1776" alt="image" src="https://user-images.githubusercontent.com/3708366/218273495-2730ea1e-14f4-4951-bf0c-cdc0f93e4c57.png">

<img width="1355" alt="image" src="https://user-images.githubusercontent.com/3708366/218273523-f51e1425-c33c-4f1d-bd4f-ffb4c7d1cd5a.png">

**Comment by mmueller2012** [comment]
Thanks for the bug report. I can reproduce the issue, seems like the URL parser of the webview treats `ABC` in `gitlens://ABC/def` as path and not hostname. This will be fixed in the next release.

What surprises me a bit is that you don't have syntax highlighting. Are you using a Dev Container or a remote session?

**Comment by worksofliam** [comment]
No dev container or remote. It's local.

**Comment by mmueller2012** [comment]
@worksofliam We just fixed a bug regarding missing syntax highlighting (not released yet). Can you let me know which VS Code theme you are using so I can verify that this fixes your issue as well?

**Comment by worksofliam** [comment]
@mmueller2012 

GitHub Light.

**Comment by mmueller2012** [comment]
We have just released SemanticDiff 0.8.2, which should fix both of the problems mentioned in this issue. Breadcrumbs should now only include the path when opening commits via GitLens, and syntax highlighting should now work correctly with third-party themes like GitHub Light.

I will close this bug report, but please let us know if it works for you.
